### ISSUE TITLE
Out-of-bounds access to LCP

### ISSUE THREAD

**Issue by DepuydtLore** [regindex/suffixient#1]
On [this line](https://github.com/regindex/suffixient/blob/9c38444678d6a8106dabfdbd094275700e86223c/suffixient.cpp#L154), the LCP array can be accessed with a value of i = N. This happens when i was incremented up until N in the while loop above. 

In debug mode, the code exits due to a failed assertion for accessing the LCP array.

**Comment by nicolaprezza** [comment]
Hi Lore, thanks for spotting this! indeed, that LCP[i] should have been min_lcp. I've checked a few small examples by hand and the code seems to always return the correct smallest suffixient set, but I don't have time for a deeper check. Please, do run plenty of tests if you have time and let me know if you spot other errors. It would be great to have a code that checks if a given set is the smallest suffixient to run more extensive tests, but I have no time right now to write it (actually, I'm not even sure how this can be done efficiently: it could be a nice problem to study).

**Comment by DepuydtLore** [comment]
Great, thank you! If I notice anything else, I will definitely let you know. And I'll think about the testing as well.
